// const shows = [
// 	{
// 		id: 1,
// 		poster: "/assets/images/slider1.jpg",
// 		name: "How to train your dragon: the hidden world",
// 		category: "movie",
// 		genres: ["action", "comedy", "drama"],
// 		authorId: 1,
// 		author: "mustafa_salah",
// 		reviews: 4,
// 		status: "published",
// 		publishDate: "2019-07-12",
// 		views: 234,
// 	},
// 	{
// 		id: 2,
// 		poster: "/assets/images/slider2.jpg",
// 		name: "Pet Sematary",
// 		category: "movie",
// 		genres: ["action", "mystry", "horror"],
// 		authorId: 1,
// 		author: "mustafa_salah",
// 		reviews: 2,
// 		status: "published",
// 		publishDate: "2019-07-16",
// 		views: 233,
// 	},
// 	{
// 		id: 3,
// 		poster: "/assets/images/slider3.jpg",
// 		name: "Toy Story 3",
// 		category: "movie",
// 		genres: ["animation", "comedy", "adventure"],
// 		authorId: 1,
// 		author: "mustafa_salah",
// 		reviews: 12,
// 		status: "published",
// 		publishDate: "2019-08-18",
// 		views: 2145,
// 	},
// 	{
// 		id: 4,
// 		poster: "/assets/images/slider4.jpg",
// 		name: "The Amazing Spiderman 2",
// 		category: "movie",
// 		genres: ["animation", "romance", "adventure"],
// 		authorId: 1,
// 		author: "aliosman",
// 		reviews: 9,
// 		status: "drafted",
// 		publishDate: "2019-08-23",
// 		views: 2355,
// 	},
// 	{
// 		id: 5,
// 		poster: "/assets/images/rec3.jpg",
// 		name: "Incridables 3",
// 		category: "movies",
// 		genres: ["animation", "action", "adventure"],
// 		authorId: 1,
// 		author: "mustafa_salah",
// 		reviews: 2,
// 		status: "published",
// 		publishDate: "2019-08-29",
// 		views: 3409,
// 	},
// 	{
// 		id: 6,
// 		poster: "/assets/images/rec4.jpg",
// 		name: "ZooTopia",
// 		category: "movies",
// 		genres: ["animation", "comedy", "adventure"],
// 		authorId: 1,
// 		author: "mohamed_mosa",
// 		reviews: 12,
// 		status: "drafted",
// 		publishDate: "2019-09-13",
// 		views: 756,
// 	},
// ];

import http from "./httpServices";

export default async function getShows() {
	const shows = await http.get("/shows");
	return shows.data;
}
