export default {
	data: {
		type: "",
		name: "",
		another_name: "",
		genres: [],
		release_year: "",
		score: "",
		rate: "nr",
		duration: "",
		season_no: "",
		episodes: "",
		status: "a",
		source: "manga",
		studio: "n/a",
		related_shows: [],
		release_date: "",
		aired_from: "",
		aired_to: "",
		story: "",
		imdb_link: "",
		mal_link: "",
		poster: "",
		background: "",
		square_image: "",
		trailer_link: "",
		tags: [],
		published: 1,
		reviews_enabled: 1,
		author: 23,
		keywords: "",
		description: "",
		gallery: [],
		arcs: {
			form: {
				id: "",
				key: "",
				no: "",
				name: "",
			},
			list: [],
		},
		watching_servers: [
			{ name: "", files: {} },
			{ name: "", code: "" },
		],
		video_files: [
			{
				raw_type: "blu-ray",
				resolution: "1080",
				size: "",
				audio: "AAC",
				language: "",
				subtitle: "",
				translator: "",
				download_servers: [
					{ name: "", file: null },
					{ name: "", link: "" },
				],
			},
		],
	},
	errors: {},
};
